### PR TITLE
Fixed unnecessary stateboard processing

### LINKED ISSUE #571: ``cartridge stop`` always stopping stateboard
```bash
cartridge stop router
   • myapp-stateboard... OK
   • myapp.router... OK
```

### PR DESCRIPTION
**Pull request by mRrvz**
Now ``stateboard: true`` specified in ``.cartridge.yml`` affects 
only ``cartridge start/stop/status/log/clean`` calls without 
arguments, e.g. ``cartridge stop router`` doesn't lead to 
stopping stateboard too, but ``cartridge stop`` stops all 
instances includes stateboard. Closes #571

### CODE REVIEW

File: cli/running/common.go [hunk 1]
```diff
@@ -83,6 +83,7 @@ func collectProcesses(ctx *context.Ctx) (*ProcessesSet, error) {
 		for _, instance := range ctx.Running.Instances {
 			process := NewInstanceProcess(ctx, instance)
 			processes.Add(process)
+
```
Comment (dokshina) [inline cli/running/common.go:86]: Redundant change.

File: cli/running/running.go [hunk 2]
```diff
@@ -50,6 +50,14 @@ func FillCtx(ctx *context.Ctx, args []string) error {
 		return err
 	}
 
+	// In order not to start (stop, log, etc) the stateboard instance when user
+	// start instances by name. e.g. ``cartridge stop router`` doesn't lead to
```
Comment (dokshina) [inline cli/running/running.go:54]: user starts

**Review by dokshina — COMMENTED** [review]
Sorry, but...

**Review by dokshina — APPROVED** [review]
Brilliant!
