### PR TITLE
Fixed an incorrect error message when trying to bootstrap vshard

### LINKED ISSUE #595: replicasets bootstrap-vshard fails with cryptic error
`cartridge replicasets bootstrap-vshard` fails with cryptic error when forget to setup replicasets first.

```bash
10:24:44 Workspace cartridge create
Enter project name [myapp]:
   • Create application myapp
   • Generate application files
   • Initialize application git repository
   • Application "myapp" created successfully
10:24:51 Workspace cd myapp
10:24:55 myapp [master] cartridge build
   • Build application in /Users/i.konyukhov/Workspace/myapp
   • Running `cartridge.pre-build`
   • Running `tarantoolctl rocks make`
   • Application was successfully built
10:25:06 myapp [master] cartridge start -d
   • myapp-stateboard... OK
   • myapp.router... OK
   • myapp.s2-master... OK
   • myapp.s1-master... OK
   • myapp.s1-replica... OK
   • myapp.s2-replica... OK
10:25:14 myapp [master] cartridge replicasets bootstrap-vshard
   ⨯ Failed to find some instance joined to cluster: %!!(MISSING)s(<nil>)
```

And with setup:

```
10:32:34 myapp [master] cartridge replicasets setup
   • Set up replicasets described in /Users/i.konyukhov/Workspace/myapp/replicasets.yml
   • router... CREATED
   • s-1... CREATED
   • s-2... CREATED
   • Replicasets are set up successfully
10:32:45 myapp [master] cartridge replicasets bootstrap-vshard
   • Vshard is bootstrapped successfully
```

Versions:

```
10:24:37 Workspace cartridge -v
Tarantool Cartridge CLI v2.9.1 darwin/amd64 commit: 5770f5e
10:24:40 Workspace tarantool -v
Tarantool Enterprise 2.7.2-0-g4d8c06890-r406-macos
Target: Darwin-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/opt/actions-runners/sdk_01/_work/sdk/sdk/build.sdk/tarantool-2.7/static-build/tarantool-prefix -DENABLE_BACKTRACE=TRUE
Compiler: /Library/Developer/CommandLineTools/usr/bin/cc /Library/Developer/CommandLineTools/usr/bin/c++
C_FLAGS: -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-gnu-alignof-expression
CXX_FLAGS: -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-invalid-offsetof -Wno-gnu-alignof-expression
```

### PR DESCRIPTION
**Pull request by mRrvz**
Fixed an incorrect error message when trying to bootstrap 
vshard with out a configured cluster. Closes #595

### CODE REVIEW

File: cli/replicasets/common.go [hunk 1]
```diff
@@ -58,10 +58,14 @@ func connectToSomeJoinedInstance(ctx *context.Ctx) (*connector.Conn, error) {
 	}
 
 	joinedInstanceName, err := getJoinedInstanceName(instancesConf, ctx)
-	if err != nil || joinedInstanceName == "" {
+	if err != nil {
 		return nil, fmt.Errorf("Failed to find some instance joined to cluster: %s", err)
 	}
 
+	if joinedInstanceName == "" {
+		return nil, fmt.Errorf("No joined to cluster instances found")
```
Comment (dokshina) [inline cli/replicasets/common.go:66]: `No instances joined to cluster found`?

**Review by dokshina — APPROVED** [review]
