### PR TITLE
Fix pack docker with centos 8

### LINKED ISSUE #687: Red docker pack integration tests
See, for example, https://github.com/tarantool/cartridge-cli/runs/5065220968?check_suite_focus=true

Fails are stable and reproduces on all Tarantool versions:
```
FAILED test/integration/pack/test_pack.py::test_custom_base_image_build_dockerfile[tgz]
```
for EE and
```
ERROR test/integration/pack/test_pack_docker.py::test_pack - AssertionError: ...
ERROR test/integration/pack/test_pack_docker.py::test_tarantool_uid_and_gid
```
for open-source.

### PR DESCRIPTION
**Pull request by 0x501D**
Centos 8 mirrors is deprecated now.
Switched to vault repo at cern.ch as a most stable one.

https://www.centos.org/centos-linux-eol

Closes #687

### CODE REVIEW

**Review by mRrvz — APPROVED** [review]

**Comment by Totktonada** [comment]
NB: https://github.com/CentOS/sig-cloud-instance-images/issues/190

File: cli/project/dockerfiles_test.go [hunk 1]
```diff
@@ -165,6 +165,13 @@ func TestGetBuildImageDockerfileTemplateEnterprise(t *testing.T) {
 
 	expLayers = `FROM centos:7
 
+### Fix Centos 8 EOL repo
```
Comment (LeonidVas) [inline cli/project/dockerfiles_test.go:168]: AFAIK usually either write everything in lower case as "centos" or "CentOS".

**Review by LeonidVas — APPROVED** [review]
I'm not so good at docker stuff, but it looks fine to me and it works.

File: cli/project/dockerfiles_test.go (hunk 1 above)
Comment (0x501D) [reply cli/project/dockerfiles_test.go]: fixed
