### PR TITLE
bugfix: specifying confusing instance names

### LINKED ISSUE #763: Support specifying confusing instance names
### 1. Application name as instance name

Now we don't support instance names which coincide with application names:

```bash
cat ./instances.yml 
---
myapp.myapp:
  advertise_uri: localhost:3301
  http_port: 8081
```
```bash
cartridge start -d
   • myapp.myapp... OK
```
```bash
cartridge status
   • myapp.myapp: RUNNING
```
```bash
cartridge status myapp
   ⨯ Application name is specified. Please, specify instance name(s)
```

### 2. Instance name with dots

The reason is this code in `GetInstancesFromArgs` method:
https://github.com/tarantool/cartridge-cli/blob/80f0f6374c320e36806e247c406a49665fc41e57/cli/common/utils.go#L385-L387

We also do not support instance names with dots:

```bash
cat ./instances.yml 
---
myapp.my.app:
  advertise_uri: localhost:3301
  http_port: 8081
```
```bash
cartridge start -d
   • myapp.my.app... OK
```
```bash
cartridge status
   • myapp.my.app: RUNNING
```
```bash
cartridge status my.app
   ⨯ [APP_NAME].INSTANCE_NAME is specified. Please, specify instance name(s)
```

The reason is this code in `GetInstancesFromArgs` method:
https://github.com/tarantool/cartridge-cli/blob/80f0f6374c320e36806e247c406a49665fc41e57/cli/common/utils.go#L389-L393

### 3. Specifying an instance name multiple times

`GetInstancesFromArgs` also doesn't allow to specify an instance multiple times:
https://github.com/tarantool/cartridge-cli/blob/80f0f6374c320e36806e247c406a49665fc41e57/cli/common/utils.go#L400-L402

------------------------------------------------------------------------------------------------------

### Proposed solution

The reason of the issues 1 and 2 is the desire to help a user if they specified `application_name` or `application_name.instance_name` instead of `instance_name`. It results in inability to use some instance names in some commands which are (likely) supported by any other command. We need to

1. allow a user to use such names
2. after verifying that any other command is fine with that.

To preserve existing helpful error messages in case user really specified `application_name` or `application_name.instance_name` instead of `instance_name` (which is rather often), we'll need to rework our approach. If user had provided an invalid info, the command should fail. And if the command had failed,

3. we additionally check if they had specified `application_name` or `application_name.instance_name` instead of `instance_name` and, if they are, add this info to error message.

Regarding issue 3, we may simply

4. start to skip duplicate names instead of throwing an error,

but, since there are no such request from customers yet, we may ignore this one for now.

Based on https://jira.vk.team/browse/TNT-765

### PR DESCRIPTION
**Pull request by GRISHNOV**
Added support for instance names:
* Application name as instance name
* Instance name with dots

Closes #763

### CODE REVIEW

File: cli/connect/connect.go [hunk 1]
```diff
@@ -33,6 +34,12 @@ func Enter(ctx *context.Ctx, args []string) error {
 
 	process := running.NewInstanceProcess(ctx, instanceName)
 	if !process.IsRunning() {
+		instanceNameParts := strings.SplitN(instanceName, ".", 2)
```
Comment (DifferentialOrange) [inline cli/connect/connect.go:37]: Let's use the same approach as it was in util before: separate check for applicationName instead of instanceName and applicationName.instanceName instead of instanceName.

File: cli/replicasets/failover_priority.go [hunk 2]
```diff
@@ -21,7 +21,7 @@ func SetFailoverPriority(ctx *context.Ctx, args []string) error {
 		return err
 	}
 
-	if ctx.Replicasets.FailoverPriorityNames, err = common.GetInstancesFromArgs(args, ctx.Project.Name); err != nil {
+	if ctx.Replicasets.FailoverPriorityNames, err = common.GetInstancesFromArgs(args); err != nil {
```
Comment (DifferentialOrange) [inline cli/replicasets/failover_priority.go:24]: So we don't get any additional info for `replicasets` command error? I think we should

File: cli/connect/connect.go (hunk 1 above)
Comment (DifferentialOrange) [reply cli/connect/connect.go:37]: You may extract it to a separate util like the one we used before, since it seems like we may reuse it in several places

File: cli/common/utils_test.go [hunk 3]
```diff
@@ -114,40 +114,16 @@ func TestGetInstancesFromArgs(t *testing.T) {
 	var args []string
 	var instances []string
 
-	projectName := "myapp"
-
-	// wrong format
-	args = []string{"myapp.instance-1", "myapp.instance-2"}
```
Comment (DifferentialOrange) [inline cli/common/utils_test.go:120]: If it is possible and not too time-consuming, we should have tests for our new approach.

**Review by DifferentialOrange — COMMENTED** [review]
Thank you for the patch. At the first glance, it seems like we do not yet covered every case we should. Please, correct me if I'm wrong.

File: cli/replicasets/failover_priority.go (hunk 2 above)
Comment (GRISHNOV) [reply cli/replicasets/failover_priority.go:24]: Done, added for replicasets `join`, `expel` and `set-failover-priority`

File: cli/common/utils_test.go (hunk 3 above)
Comment (GRISHNOV) [reply cli/common/utils_test.go:120]: Added unit test

File: cli/common/utils.go [hunk 4]
```diff
@@ -409,6 +399,17 @@ func GetInstancesFromArgs(args []string, projectName string) ([]string, error) {
 	return instances, nil
 }
 
+func CheckInstanceNameTypoWithProjectName(instanceName string, projectName string, errDesc string) error {
+	instanceNameParts := strings.SplitN(instanceName, ".", 2)
+	if instanceNameParts[0] == projectName {
+		return fmt.Errorf(errDesc+
+			"You may have specified an unnecessary prefix as the application name, "+
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply cli/common/utils.go]: Done

**Review by DifferentialOrange — COMMENTED** [review]
Sorry, I have forgot to submit this batch of comments

File: cli/common/utils.go [hunk 5]
```diff
@@ -409,6 +399,17 @@ func GetInstancesFromArgs(args []string, projectName string) ([]string, error) {
 	return instances, nil
 }
 
+func CheckInstanceNameTypoWithProjectName(instanceName string, projectName string, errDesc string) error {
+	instanceNameParts := strings.SplitN(instanceName, ".", 2)
+	if instanceNameParts[0] == projectName {
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply cli/common/utils.go:407]: Done

File: cli/common/utils.go [hunk 6]
```diff
@@ -409,6 +399,17 @@ func GetInstancesFromArgs(args []string, projectName string) ([]string, error) {
 	return instances, nil
 }
 
+func CheckInstanceNameTypoWithProjectName(instanceName string, projectName string, errDesc string) error {
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply cli/common/utils.go]: Done, now `CheckInstanceNameCommonMisprint`

File: cli/running/process.go [hunk 7]
```diff
@@ -390,6 +390,16 @@ func NewStateboardProcess(ctx *context.Ctx) *Process {
 
 func (process *Process) Log(follow bool, n int) error {
 	if _, err := os.Stat(process.logFile); err != nil {
+		if os.IsNotExist(err) {
+			logFilePathParts := strings.SplitN(process.logFile, "/", -1)
+			logFileName := logFilePathParts[len(logFilePathParts)-1]
+			logFilePathParts[len(logFilePathParts)-1] = strings.SplitN(logFileName, ".", 2)[1]
+			possibleLogFilePath := strings.Join(logFilePathParts, "/")
+			if _, err := os.Stat(possibleLogFilePath); err == nil {
+				return fmt.Errorf("Failed to use process log file: " +
```
Comment (DifferentialOrange) [inline cli/running/process.go:399]: Can you reuse existing util here too?

File: cli/replicasets/expel.go [hunk 8]
```diff
@@ -64,6 +65,10 @@ func Expel(ctx *context.Ctx, args []string) error {
 
 	for instanceName, instanceFound := range instancesToExpelMap {
 		if !instanceFound {
+			if err := common.CheckInstanceNameTypoWithProjectName(instanceName, ctx.Project.Name,
+				fmt.Sprintf("Instance %s isn't found in cluster: ", instanceName)); err != nil {
```
[the remark this answers is not in the document]
Comment (DifferentialOrange) [reply cli/replicasets/expel.go:69]: Yes. I think we may simply return the error in wrapper. Wrapper should add useful comment, if it makes sence, and return the same unwrapped error otherwise.

[the remark this answers is not in the document]
Comment (GRISHNOV) [reply cli/replicasets/expel.go]: Done

File: cli/running/process.go (hunk 7 above)
Comment (GRISHNOV) [reply cli/running/process.go:399]: Hmm, it looks like it can only be moved to `utils`, since the check logic is different here

Comment (DifferentialOrange) [reply cli/running/process.go:399]: You can wrap this error on the upper level in `cli/running/running.go`. You can do the same for `Status` too (we decided not to wrap this one in the start, but if you implement this in `Log`, implementing this for `Status` would be a 10 seconds task).

Comment (GRISHNOV) [reply cli/running/process.go]: Done for `Log`

AFAIU, it is not possible to implement this check at the same level for the`Status`

May be it is possible to do this at a lower level (like for `Log` before), but now we have a print:
```
./cartridge status mytestapp.mytestapp                             
   • mytestapp.mytestapp.mytestapp: NOT STARTED
```

I mean, here users can see that there is an extra unnecessary prefix of the specified name before `NOT STARTED`. Do we need a check here?

File: cli/common/utils.go [hunk 9]
```diff
@@ -582,7 +586,9 @@ func ContainsUpperSymbols(src string) bool {
 
 const (
 	appNameSpecifiedError = "Application name is specified. " +
-		"Please, specify instance name(s)"
-	instanceIDSpecified = `[APP_NAME].INSTANCE_NAME is specified. ` +
-		"Please, specify instance name(s)"
+		"You may have made a misprint. " +
```
Comment (DifferentialOrange) [inline cli/common/utils.go:589]: I think the "typo" word is more widely used in such cases

File: cli/running/process.go (hunk 7 above)
Comment (DifferentialOrange) [reply cli/running/process.go]: Let's forget about the status then

File: cli/common/utils.go (hunk 9 above)
Comment (GRISHNOV) [reply cli/common/utils.go]: Done

File: cli/running/process.go (hunk 7 above)
Comment (DifferentialOrange) [reply cli/running/process.go]: It seems to be even more interesting than that: you can start and stop instances with arbitrary names, see https://github.com/tarantool/cartridge-cli/issues/766

We decided not to cover this issue in this PR

**Review by DifferentialOrange — APPROVED** [review]
