### PR TITLE
version: fix parsing Cartridge version

### LINKED ISSUE #749: replicasets setup doesn't work on Tarantool EE and Cartridge scm-1
Cartridge-cli version 2.12.2
```
cartridge replicasets setup --bootstrap-vshard
   • Set up replicasets described in /Users/yngvar_antonsson/Work/myapp/replicasets.yml
   ⨯ Failed to get Cartridge version: Failed to parse Tarantool version: Malformed version: unknown
yngvar_antonsson@MacBook-Pro-Igor myapp % tarantool
Tarantool Enterprise 2.11.0-entrypoint-55-ga74aeaf7c-r508
```

### PR DESCRIPTION
**Pull request by yngvar-antonsson**
I didn't forget about

- [ ] Tests
- [ ] Changelog
- [ ] Documentation

Closes #749

### CODE REVIEW

File: cli/common/tarantool.go [hunk 1]
```diff
@@ -327,13 +327,13 @@ func GetMajorCartridgeVersion(conn *connector.Conn) (int, error) {
 		return 0, err
 	}
 
-	if cartridgeVersionStr == "scm-1" {
+	if cartridgeVersionStr == "scm-1" || cartridgeVersionStr == "unknown" {
```
Comment (DifferentialOrange) [inline cli/common/tarantool.go:330]: By using git blame, you can trace that `unknown` version could be retrieved from the latest `cluster` rock and from any version of `cartridge`, including 1.x ones:

https://github.com/tarantool/cartridge/commit/038a163f14a76a5fdc962d28b1e9d4460ce72245

So cartridgeVersionStr == "unknown" may mean `1, nil` and `2, nil`.

Comment (yngvar-antonsson) [reply cli/common/tarantool.go]: Ok, then let's do the error message more clear

**Review by DifferentialOrange — APPROVED** [review]
