### PR TITLE
Fixed project build fail with capital letters in name

### LINKED ISSUE #610: Failed to build project with capital letters in the name
```
$ cartridge create
Enter project name [myapp]: Myapp
   • Create application Myapp 
   • Generate application files
   • Initialize application git repository
   • Application "Myapp" created successfully
$ cd Myapp 
$ cartridge build
   • Build application in /Users/aleksei.romanov/repos/cli/Myapp
   • Running `cartridge.pre-build`
   • Running `tarantoolctl rocks make`
| 

Error: Inconsistency between rockspec filename (Myapp-scm-1.rockspec) and its contents (myapp-scm-1.rockspec).
   ⨯ Failed to install rocks: Failed to run 
/usr/local/bin/tarantoolctl rocks make

exit status 1
```

### PR DESCRIPTION
**Pull request by mRrvz**
Fixed project build (``cartridge build`` command) fail with capital letters 
 in the project name.

Closes #610

### CODE REVIEW

File: cli/create/templates/templates.go [hunk 1]
```diff
@@ -72,6 +72,13 @@ func Instantiate(ctx *context.Ctx) error {
 		return fmt.Errorf("Failed to instantiate project template: %s", err)
 	}
 
+	spec, err := common.FindRockspec(ctx.Project.Path)
+	if err != nil {
+		return fmt.Errorf("Failed to find rockspec file in project template: %s", err)
+	}
+
+	os.Rename(spec, strings.ToLower(spec))
```
Comment (AnaNek) [inline cli/create/templates/templates.go:80]: Does it work correct only with `cartridge create` command? I suppose it would fail if we pass rockspec file by using `--spec` flag like `cartridge build MyApp --spec MyApp/MyApp-scm-2.rockspec`. Maybe we should leave some note in doc that rockspec should be passed in lower case?

Comment (mRrvz) [reply cli/create/templates/templates.go:80]: I agree, it should fall if the user passes in an incorrect (with capital letters) spec. Can you please add this note to your patch #616 ?

Comment (AnaNek) [reply cli/create/templates/templates.go:80]: Ok, done

File: cli/build/build.go [hunk 2]
```diff
@@ -63,6 +63,10 @@ func Run(ctx *context.Ctx) error {
 		}
 
 		ctx.Build.Spec = filepath.Base(ctx.Build.Spec)
+
+		if common.ContainsUpperSymbols(ctx.Build.Spec) {
+			return fmt.Errorf("Name of the .rockspec file mustn't contain capital letters")
```
Comment (AnaNek) [inline cli/build/build.go:68]: How about to add this check for `cartridge pack` too? `--spec` flag is used for pack too.

Comment (mRrvz) [reply cli/build/build.go:68]: ``cartridge pack`` calls this function (``build.Run``) so checking is already enabled:

```
~/repos/cartridge-cli   fix-build-capital-letters-project-name  ./cartridge pack tgz MyApp --spec=MyApp/MyApp-scm-1.rockspec 
   • Packing MyApp into tgz   
   • Temporary directory is set to /Users/aleksei.romanov/.cartridge/tmp/pack-zfumiuqa4g
   • Initialize application dir
   • Build application in /Users/aleksei.romanov/.cartridge/tmp/pack-zfumiuqa4g/package-files/MyApp
   ⨯ Name of the .rockspec file mustn't contain capital letters
```

Comment (AnaNek) [reply cli/build/build.go]: Ok, thanks

File: test/integration/build/test_build.py [hunk 3]
```diff
@@ -261,3 +279,24 @@ def test_verbosity(cartridge_cmd, project_without_dependencies):
     assert all([log not in output for log in build_logs])
     assert 'Failed to run pre-build hook' in output
     assert prebuild_output in output
+
+
+def test_capital_letters_name_rockspec(cartridge_cmd, project_with_capital_letters_name):
+    project = project_with_capital_letters_name
+    cmd = [cartridge_cmd, "build"]
+
+    rc, _ = run_command_and_get_output(cmd, cwd=project.path)
```
Comment (AnaNek) [inline test/integration/build/test_build.py:288]: Maybe just `subprocess.run(cmd, cwd=project.path)`?

File: test/integration/build/test_build.py [hunk 4]
```diff
@@ -7,7 +7,25 @@
 from utils import run_command_and_get_output
 from utils import get_rockspec_path
 
+from project import Project
+from project import INIT_NO_CARTRIDGE_FILEPATH
 from project import set_and_return_whoami_on_build
+from project import remove_all_dependencies, remove_project_file, replace_project_file
+
+
+@pytest.fixture(scope="function")
```
Comment (LeonidVas) [inline test/integration/build/test_build.py:16]:
```
# ########
# Fixtures
# ########
```

File: test/integration/build/test_build.py [hunk 5]
```diff
@@ -7,7 +7,25 @@
 from utils import run_command_and_get_output
 from utils import get_rockspec_path
 
+from project import Project
+from project import INIT_NO_CARTRIDGE_FILEPATH
 from project import set_and_return_whoami_on_build
+from project import remove_all_dependencies, remove_project_file, replace_project_file
```
Comment (LeonidVas) [inline test/integration/build/test_build.py:13]: As I can see in the code, preference is given to "one" imports per line.
```
from project import remove_all_dependencies
from project import remove_project_file
from project import replace_project_file
```

File: test/integration/build/test_build.py [hunk 6]
```diff
@@ -7,7 +7,25 @@
...
+
+
+@pytest.fixture(scope="function")
+def project_with_capital_letters_name(cartridge_cmd, short_tmpdir):
+    project = Project(cartridge_cmd, 'App-withoutDependencies01', short_tmpdir, 'cartridge')
+
+    remove_all_dependencies(project)
+
+    # This is necessary, because default app config has parameter `stateboard: true`
```
Comment (LeonidVas) [inline test/integration/build/test_build.py:22]: Use something like "Remove file with Cartridge configuration" instead of "This".

**Review by LeonidVas — CHANGES_REQUESTED** [review]
Hi! Thank you for the patch.
AFAIU before push to master all commits will be squashed to one. What is the title and message commit will be have?
See several commits below.

**Comment by mRrvz** [comment]
Usually, I make the commit message the same as the description of PR.

@LeonidVas

File: cli/build/build.go [hunk 7]
```diff
@@ -63,6 +63,10 @@ func Run(ctx *context.Ctx) error {
 		}
 
 		ctx.Build.Spec = filepath.Base(ctx.Build.Spec)
+
+		if common.ContainsUpperSymbols(ctx.Build.Spec) {
+			return fmt.Errorf("Please specify rockspec filename in lower case")
+		}
```
[the remark this answers is not in the document]
Comment (mRrvz) [reply cli/build/build.go:69]: I also think that we should show an error, not a warning.

**Review by LeonidVas — APPROVED** [review]
