### PR TITLE
Fix errors on cartridge cli different commands

### LINKED ISSUE #697: Sometimes get errors on cartridge cli different commands - Failed to dial
Hi, i'm newbe to tarantool, tried to install default cluster from docs with myapp. During configuration and after configuration the cluster I sometimes get errors "*Failed to dial*" on different cli commands. My config is on el8 , on 2 different hosts on same net.
cartridge version 
  Tarantool Cartridge CLI
   Version:       2.12.0
   OS/Arch:       linux/amd64
   Git commit:    b4ed1a2
 Tarantool Cartridge
   Version:       2.7.3-1

During config get errors on different commands , but entering same commands again same time everything goes OK. No errors in instance logs during commands. 
Examples of sometimes failed commands while getting "Failed to dial: dial unix /var/lib/tarantool/myapp/tmp/run/myapp.***.control: connect" :
   cartridge replicasets join --replicaset s-1 s1-master s1-replica
   cartridge replicasets add-roles   --replicaset router vshard-router app.roles.custom failover-coordinator metrics  
   cartridge replicasets list
Make some small test (see logs, hide IP by xxx) 
[cartridge_cli_github.log](https://github.com/tarantool/cartridge-cli/files/8452115/cartridge_cli_github.log)

### PR DESCRIPTION
**Pull request by psergee**
cartridge cli performs some commands via connection
to cluster member control socket. When it looks for
an instance to connect to it does not filter out remote
instances. But such instances do not have sockets on the
system where cartridge cli is invoked.
The solution is to use only local instances to perform
any operations.

Resolves #697

### CODE REVIEW

File: cli/cluster/instances.go [hunk 1]
```diff
@@ -30,12 +30,12 @@ func ConnectToSomeRunningInstance(ctx *context.Ctx) (*connector.Conn, error) {
 		return nil, fmt.Errorf("Failed to get instances configuration: %s", err)
 	}
 
-	runningInstancesNames := getRunningInstances(instancesConf, ctx)
-	if len(runningInstancesNames) == 0 {
+	runningInstances := getRunningInstances(instancesConf, ctx)
+	instanceName, ok := GetFirstInstanceName(runningInstances)
+	if !ok {
```
Comment (better0fdead) [inline cli/cluster/instances.go:35]: Perhaps we dont need to return 2 values from GetFirstInstanceName,
 why couldnt we just check: `if instanceName == ""{
...
}`

File: cli/cluster/instances.go [hunk 2]
```diff
@@ -102,13 +102,22 @@ func GetInstancesConf(ctx *context.Ctx) (*InstancesConf, error) {
 	return &instancesConf, nil
 }
 
+// Removes non-local members from instances map
```
Comment (better0fdead) [inline cli/cluster/instances.go:105]: https://go.dev/blog/godoc 
`Notice this comment is a complete sentence that begins with the name of the element it describes.`

File: cli/cluster/instances.go [hunk 3]
```diff
@@ -141,14 +150,15 @@ func ConnectToInstance(instanceName string, ctx *context.Ctx) (*connector.Conn,
 	return conn, nil
 }
 
-func getRunningInstances(instancesConf *InstancesConf, ctx *context.Ctx) []string {
-	var runningInstancesNames []string
-	for instanceName := range *instancesConf {
+// Returns URI -> instance name map of running instances
```
Comment (better0fdead) [inline cli/cluster/instances.go:153]: https://go.dev/blog/godoc 
`Notice this comment is a complete sentence that begins with the name of the element it describes.`

File: cli/cluster/membership.go [hunk 4]
```diff
@@ -24,24 +24,34 @@ func (membershipInstance *MembershipInstance) DecodeMsgpack(d *msgpack.Decoder)
...
 // First, it connects all instances to membership (probes all running instances by one
 // of them). Then, it gets all membership instances members.
-func GetMembershipInstances(instancesConf *InstancesConf, ctx *context.Ctx) (*MembershipInstances, error) {
-	runningInstancesNames := getRunningInstances(instancesConf, ctx)
-	if len(runningInstancesNames) == 0 {
+func GetMembershipInstances(instancesConf *InstancesConf, ctx *context.Ctx,
+	filters ...InstancesFilter) (*MembershipInstances, error) {
+	runningInstances := getRunningInstances(instancesConf, ctx)
+	instanceName, ok := GetFirstInstanceName(runningInstances)
+	if !ok {
```
Comment (better0fdead) [inline cli/cluster/membership.go:43]: Perhaps we dont need to return 2 values from GetFirstInstanceName,
 why couldnt we just check: `if instanceName == ""{
...
}`

File: cli/cluster/membership.go [hunk 5]
```diff
@@ -24,24 +24,34 @@ func (membershipInstance *MembershipInstance) DecodeMsgpack(d *msgpack.Decoder)
...
 }
 
+func GetFirstInstanceName(instances map[string]string) (string, bool) {
+	for _, instanceName := range instances {
+		return instanceName, true
+	}
+	return "", false
+}
+
+type InstancesFilter func(*MembershipInstances, map[string]string)
```
Comment (better0fdead) [inline cli/cluster/membership.go:34]: Probably, move type definition to the begining of the file. Also you can add a description to it.

File: cli/cluster/membership.go [hunk 6]
```diff
@@ -24,24 +24,34 @@ func (membershipInstance *MembershipInstance) DecodeMsgpack(d *msgpack.Decoder)
 	return common.DecodeMsgpackStruct(d, membershipInstance)
 }
 
+func GetFirstInstanceName(instances map[string]string) (string, bool) {
```
Comment (better0fdead) [inline cli/cluster/membership.go:27]: Write a description to this function, please.

**Review by better0fdead — CHANGES_REQUESTED** [review]
Hi! Thank you for the patch. 
Add a submodule name to the beginning of the commit title: "submodule : commit title".

File: cli/cluster/instances.go (hunk 1 above)
Comment (psergee) [reply cli/cluster/instances.go]: Agree.

File: cli/cluster/instances.go [hunk 7]
```diff
@@ -102,13 +102,22 @@ func GetInstancesConf(ctx *context.Ctx) (*InstancesConf, error) {
 	return &instancesConf, nil
 }
 
+// filterRunningMembers removes non-local members from instances map
```
Comment (better0fdead) [inline cli/cluster/instances.go:105]: Add dot to the end of the sentence.

**Review by better0fdead — APPROVED** [review]
LGTM

File: cli/cluster/instances.go [hunk 8]
```diff
@@ -102,13 +102,22 @@ func GetInstancesConf(ctx *context.Ctx) (*InstancesConf, error) {
...
+// filterRunningMembers removes non-local members from instances map.
+func filterRunningMembers(membershipInstances *MembershipInstances, runningInstances map[string]string) {
+	for URI := range *membershipInstances {
+		if _, found := runningInstances[URI]; !found {
+			delete(*membershipInstances, URI)
+		}
+	}
+}
+
 // GetJoinedInstanceName returns a name of instancethat is already joined to cluster
```
Comment (LeonidVas) [inline cli/cluster/instances.go:114]: Hmm, now it will only return local instances. If this is ok, it should be reflected in the description and in the name of the function.

File: cli/cluster/instances.go [hunk 9]
```diff
@@ -129,6 +138,7 @@ func GetJoinedInstanceName(instancesConf *InstancesConf, ctx *context.Ctx) (stri
 	return joinedInstanceName, nil
 }
 
+// ConnectToInstance opens connection to instance control socket.
```
Comment (LeonidVas) [inline cli/cluster/instances.go:141]: "to instance **via** control socket"?

File: cli/cluster/membership.go [hunk 10]
```diff
@@ -20,28 +20,40 @@ type MembershipInstance struct {
...
+type InstancesFilter func(*MembershipInstances, map[string]string)
+
 func (membershipInstance *MembershipInstance) DecodeMsgpack(d *msgpack.Decoder) error {
 	return common.DecodeMsgpackStruct(d, membershipInstance)
 }
 
+// GetFirstInstanceName returns first instance name from the map.
+// Empty string is returned if the map is empty.
+func GetFirstInstanceName(instances map[string]string) string {
+	for _, instanceName := range instances {
```
Comment (LeonidVas) [inline cli/cluster/membership.go:32]: I'm surprised, but this is really typical code for getting a random item from a map)
I don't know how much the wording "first" is fair for the map, but that's up to you.

File: cli/cluster/membership.go [hunk 11]
```diff
@@ -50,17 +62,22 @@ func GetMembershipInstances(instancesConf *InstancesConf, ctx *context.Ctx) (*Me
...
+func ConnectToMembership(conn *connector.Conn, runningInstancesNames map[string]string,
+	instancesConf *InstancesConf) error {
+	// probe all running instances mentioned in topology
 	var urisToProbe []string
 
 	for _, instanceName := range runningInstancesNames {
 		instanceConf, found := (*instancesConf)[instanceName]
 		if !found {
-			return fmt.Errorf("Instance %s  isn't found in instances config", instanceName)
+			return fmt.Errorf("Instance %s isn't found in instances config", instanceName)
```
Comment (LeonidVas) [inline cli/cluster/membership.go:80]: In general, I don't mind fixing some stuff while working on a patch, but it's better to do it in separate commits.
https://github.com/tarantool/tarantool/wiki/Code-review-procedure#general-coding-points-to-check

> `Don't do a change if it is not related to the patch...`

**Review by LeonidVas — COMMENTED** [review]
Hi! Thank you for the patch. Generally I'm OK. See several commits bellow.
replicasets: Fix errors on cartridge cli commands

File: cli/cluster/membership.go (hunk 11 above)
Comment (psergee) [reply cli/cluster/membership.go:80]: So, should I open a separate PR for removing this extra space? :)

File: cli/cluster/instances.go [hunk 12]
```diff
@@ -102,13 +102,22 @@ func GetInstancesConf(ctx *context.Ctx) (*InstancesConf, error) {
 	return &instancesConf, nil
 }
 
+// filterRunningMembers removes non-local members from instances map.
+func filterRunningMembers(membershipInstances *MembershipInstances, runningInstances map[string]string) {
```
[the remark this answers is not in the document]
Comment (psergee) [reply cli/cluster/instances.go]: Renamed.

File: cli/cluster/instances.go (hunk 9 above)
Comment (psergee) [reply cli/cluster/instances.go]: Comment removed :)

File: cli/cluster/membership.go (hunk 10 above)
Comment (psergee) [reply cli/cluster/membership.go:32]: I was thinking about the same: "random" instead of "first". Done.

File: cli/cluster/membership.go [hunk 13]
```diff
@@ -20,28 +20,40 @@ type MembershipInstance struct {
...
+	return ""
+}
+
 // GetMembershipInstances returns MembershipInstances for currently configured instances
 // First, it connects all instances to membership (probes all running instances by one
 // of them). Then, it gets all membership instances members.
-func GetMembershipInstances(instancesConf *InstancesConf, ctx *context.Ctx) (*MembershipInstances, error) {
-	runningInstancesNames := getRunningInstances(instancesConf, ctx)
-	if len(runningInstancesNames) == 0 {
+func GetMembershipInstances(instancesConf *InstancesConf, ctx *context.Ctx,
```
[the remark this answers is not in the document]
Comment (psergee) [reply cli/cluster/membership.go:42]: Added.

File: cli/cluster/membership.go [hunk 14]
```diff
@@ -50,17 +62,22 @@ func GetMembershipInstances(instancesConf *InstancesConf, ctx *context.Ctx) (*Me
...
+	}
+
 	return membershipInstances, nil
 }
 
-func ConnectToMembership(conn *connector.Conn, runningInstancesNames []string, instancesConf *InstancesConf) error {
-	// probe all instances mentioned in topology
+func ConnectToMembership(conn *connector.Conn, runningInstancesNames map[string]string,
+	instancesConf *InstancesConf) error {
+	// probe all running instances mentioned in topology
```
[the remark this answers is not in the document]
Comment (psergee) [reply cli/cluster/membership.go]: Done.

File: cli/cluster/instances.go (hunk 9 above)
Comment (LeonidVas) [reply cli/cluster/instances.go]: > Comment removed :)

You chose the easy way)

File: cli/cluster/membership.go (hunk 11 above)
Comment (LeonidVas) [reply cli/cluster/membership.go:81]: > So, should I open a separate PR for removing this extra space? :)

OMG, NO!

Comment (LeonidVas) [reply cli/cluster/membership.go:81]: If I make several such edits in PR - I just squash them into one common (like `syntax fix`) commit or something like that. And they don't interfere reviewer looking at the rest code.

**Review by LeonidVas — APPROVED** [review]
LGTM.
