### PR TITLE
Custom centos repo support for `cartridge pack` command added

### LINKED ISSUE #469: [1pt] Building does not work with сentos image from custom repo
We have docker repository in the internal network, like this `example.com/base-image/centos:8`
I point this repository to *Dockerfile.build.cartridge* and run `cartridge pack docker`

```console
$ cartridge pack docker --sdk-local --version 0.0.1
   • Packing test-tarantool-app into docker
   • Temporary directory is set to /.../tmp/pack-kkn8oai5rf
   ⨯ Invalid base runtime Dockerfile /.../Dockerfile.cartridge: The base image must be centos:8
```

### PR DESCRIPTION
**Pull request by mRrvz**
Allowed to use any base docker image for the ``cartridge pack`` command. Closes #469

### CODE REVIEW

**Comment by dokshina** [comment]
What about some test? 

Moreover, maybe we should allow any base image, but show a warning that we've expected `centos`. Somebody can build his own centos-based image and push it to some repo with `my-cute-base-image` name.

File: cli/project/dockerfiles_test.go [hunk 1]
```diff
@@ -23,7 +23,6 @@ func TestCheckBaseDockerfile(t *testing.T) {
 	assert := assert.New(t)
 
 	var err error
-	baseImageError := "The base image must be centos:8"
```
Comment (dokshina) [inline cli/project/dockerfiles_test.go:26]: I think that all below checks of base image can be removed.

File: test/integration/pack/test_pack.py [hunk 2]
```diff
@@ -598,8 +598,8 @@ def test_invalid_base_build_dockerfile(cartridge_cmd, project_without_dependenci
 
         rc, output = run_command_and_get_output(cmd, cwd=tmpdir)
         assert rc == 1
-        assert 'Invalid base build Dockerfile' in output
-        assert 'base image must be centos:8' in output
+        assert 'Failed to build base image' in output
+        assert 'The centos:8 image is expected to be used' in output
```
Comment (dokshina) [inline test/integration/pack/test_pack.py:602]: I think it would be better to check that using `FROM some-cute-name-for-centos:8` completes successfully, but shows a warning.

Using `alexeymrvz/my-custom-centos8` isn't a good solution for tests, you can create such image locally (as a fixture) using python docker module.

Comment (dokshina) [reply test/integration/pack/test_pack.py:602]: The same for `test_pack_docker.py::test_custom_base_runtime_dockerfile `

File: cli/project/dockerfiles.go [hunk 3]
```diff
@@ -145,7 +146,7 @@ func CheckBaseDockerfile(dockerfilePath string) error {
 
 	fromLine = strings.ToLower(fromLine)
 	if !fromLayerRegexp.MatchString(fromLine) {
-		return fmt.Errorf("The base image must be centos:8")
+		log.Warnf("The centos:8 image is expected to be used")
```
Comment (dokshina) [inline cli/project/dockerfiles.go:149]: Maybe `Image based on centos:8 is expected to be used`?

File: test/integration/pack/test_pack.py [hunk 4]
```diff
@@ -92,6 +93,15 @@ def deb_archive(cartridge_cmd, tmpdir, light_project, request):
     return Archive(filepath=filepath, project=project)
 
 
+@pytest.fixture(scope="session")
+def docker_custom_image(session_tmpdir, request, docker_client):
```
Comment (dokshina) [inline test/integration/pack/test_pack.py:97]: `docker_custom_image` -> `custom_base_image`?

File: test/integration/pack/test_pack_docker.py [hunk 5]
```diff
@@ -146,25 +146,24 @@ def test_pack(docker_image, tmpdir, docker_client):
...
-def test_invalid_base_runtime_dockerfile(cartridge_cmd, project_without_dependencies, module_tmpdir, tmpdir):
-    invalid_dockerfile_path = os.path.join(tmpdir, 'Dockerfile')
-    with open(invalid_dockerfile_path, 'w') as f:
+def test_custom_base_runtime_dockerfile(cartridge_cmd, project_without_dependencies, module_tmpdir, tmpdir):
+    custom_base_dockerfile_path = os.path.join(tmpdir, 'Dockerfile')
+    with open(custom_base_dockerfile_path, 'w') as f:
         f.write('''
-            # Invalid dockerfile
-            FROM ubuntu:xenial
+            # Non standard dockerfile
```
Comment (dokshina) [inline test/integration/pack/test_pack_docker.py:153]: Non standard base image?

**Review by dokshina — COMMENTED** [review]
Please, update Changelog and check if doc should be updated (I sure it is). Also please take a look at the Dockerfiles from application template (there are comment that can contain messages about using non centos:8-based images).

**Review by dokshina — APPROVED** [review]
Brilliant!
