### PR TITLE
Prettify `cartridge start/stop` logs

### LINKED ISSUE #213: Prettify start/stop logs
Now `start` and `stop` commands use `assert` for failing on errors.
Since we use coloured logs for other commands, we can use it for `start` and `stop` commands as well.

### PR DESCRIPTION
**Pull request by dokshina**
Closes #213

### CODE REVIEW

File: cartridge-cli.lua [hunk 1]
```diff
@@ -472,33 +466,31 @@ local function detect_git_version(source_dir)
...
-
-local function detect_name(source_dir)
-    local rockspec_filename, err = find_rockspec(source_dir)
-    if rockspec_filename == nil then return nil, err end
 
-    local rockspec_filepath = fio.pathjoin(source_dir, rockspec_filename)
-    local rockspec, err = utils.load_variables_from_file(rockspec_filepath)
-    if rockspec == nil then
-        return nil, string.format('Failed to load rockspec %s: %s', rockspec_filepath, err)
+    local rockspecs = fio.glob(fio.pathjoin(dir, '*-scm-1.rockspec'))
```
Comment (olegrok) [inline cartridge-cli.lua:474]: why scm only?

Comment (olegrok) [reply cartridge-cli.lua:474]: `string.endswith(file, '.rockspec')` was before. I could use `app-1.1.0-1.rockspec` - it is not scm

File: cartridge-cli.lua [hunk 2]
```diff
@@ -472,33 +466,31 @@ local function detect_git_version(source_dir)
...
+    if #rockspecs == 1 then
+        return rockspecs[1]
     end
 
-    local name = rockspec.package
-    if name == nil then
-        return nil, string.format("Rockspec %s doesn't contain required field 'package'", rockspec_filepath)
+    if #rockspecs > 1 then
+        return nil, string.format('Found multiple rockspecs in %s', dir)
```
Comment (olegrok) [inline cartridge-cli.lua:480]: Could I specify directly rockspec/version that I need?

Comment (dokshina) [reply cartridge-cli.lua:480]: You can specify appname explicitly. In fact, you have to do it, if appname can't be detected from rockspec.

File: cartridge-cli.lua (hunk 1 above)
Comment (dokshina) [reply cartridge-cli.lua:474]: I agree, I will use `*.rockspec`pattern and fetch package name from `package` sprcified in rockspec.

File: cartridge-cli.lua [hunk 3]
```diff
@@ -3735,10 +3805,46 @@ function cmd_stop.callback(args)
...
     if fio.stat(pid_file) then
-        assert(fio.unlink(pid_file))
+        if not fio.unlink(pid_file) then
+            warn('Failed to remove pid file (%s)', pid_file)
+        end
     end
     if fio.stat(args.console_sock) then
-        assert(fio.unlink(args.console_sock))
+        if not fio.unlink(args.console_sock) then
+            warn('Failed to remove console sock (%s)', args.console_sock)
```
Comment (olegrok) [inline cartridge-cli.lua:3814]: `sock -> socket`

File: cartridge-cli.lua [hunk 4]
```diff
@@ -3735,10 +3805,46 @@ function cmd_stop.callback(args)
...
+end
+
+local function stop_all(args)
+    local instance_names = get_configured_isntances(args.cfg, args.app_name)
+    for _, instance_name in pairs(instance_names) do
+        local instance_args = table.copy(args)
+        instance_args.instance_name = instance_name
+        local ok, err = stop_one(instance_args)
+        if not ok then
+            return nil, string.format('Failed to stop %s: %s', instance_name, err)
```
Comment (olegrok) [inline cartridge-cli.lua:3835]: I'm not sure that we should do it a such way.

We should call "stop" for each instance and in case of errors we should accumulate error messages. E.g. we can't stop first instance, but we stop second and third and print error.
```
[instance_name_1] failed to stop: error_message1
[instance_name_4] failed to stop: error_message4
```

File: cartridge-cli.lua [hunk 5]
```diff
@@ -3505,82 +3590,88 @@ function Process:initialize()
...
-    execve(arg[-1], {self.script}, self.env) -- stops execution
-end
-
 function Process:build_notify_socket()
-    local sock = assert(socket('AF_UNIX', 'SOCK_DGRAM', 0), 'Can not create socket')
+    local sock = socket('AF_UNIX', 'SOCK_DGRAM', 0)
+    if sock == nil then return nil, 'Cannot create notify socket' end
+
     local basename = self.app_name .. '.' .. self.instance_name .. '-notify.sock'
     local sock_name = fio.pathjoin(self.run_dir, basename)
```
Comment (olegrok) [inline cartridge-cli.lua:3609]: Please, verify socket length - https://github.com/tarantool/tarantool/issues/4634

Comment (dokshina) [reply cartridge-cli.lua:3613]: For notify socket: https://github.com/tarantool/cartridge-cli/issues/214
For instance socket: https://github.com/tarantool/cartridge/issues/790

File: cartridge-cli.lua [hunk 6]
```diff
@@ -192,30 +192,25 @@ end
...
 local function info(fmt, ...) -- luacheck: no unused
     local msg = string.format(fmt, ...)
-    print_and_flush(colored_msg(msg, INFO_COLOR_CODE))
+    log.info(colored_msg(msg, INFO_COLOR_CODE))
 end
 
 local function debug(fmt, ...) -- luacheck: no unused
     local msg = string.format(fmt, ...)
-    print_and_flush(colored_msg(msg, DEBUG_COLOR_CODE))
+    log.info(colored_msg(msg, DEBUG_COLOR_CODE))
```
Comment (olegrok) [inline cartridge-cli.lua:213]: debug -> info? But it's ok because by default we can't log in debug mode without box.cfg
